name: Benchmark
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: lscpu
      - run: npm install
      - run: echo "${GITHUB_WORKSPACE}/build/bin/zig" >> $GITHUB_PATH
      - run: npm run --silent benchmark -- --iterations=50 --battles=100000 --normalize | tee benchmark.json
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customBiggerIsBetter'
          output-file-path: benchmark.json
          benchmark-data-dir-path: ''
          alert-threshold: '120%'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          auto-push: true
          save-data-file: ${{ github.event_name != 'pull_request' }}
