name: Fuzz
on:
  schedule:
    - cron: '36 */6 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        gen: [1]
        options: ['', '-Dshowdown']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: npm install --ignore-scripts
      - run: zig build -Doptimize=ReleaseSafe ${{matrix.options}} fuzz -- ${{matrix.gen}} 15m
      # - run: |
      #     node src/bin/install-pkmn-engine --options="-Dshowdown -Dtrace"
      #     npm run integration -- --gen=${{matrix.gen}} --duration=15m
      #   if: ${{ matrix.options != '' }}
