name: Fuzz
on:
  schedule:
    - cron: '36 */6 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        gen: [1]
        options: ['', '-Dshowdown']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: npm install
      - run: zig build -Dstage2 -Drelease-safe ${{matrix.options}} fuzz -- ${{matrix.gen}} 15m
      - run: npm run integration -- --gen=${{matrix.gen}} --cycles=100
        if: ${{ matrix.options != '' }}
