name: Fuzz
on: workflow_dispatch
# on:
#   schedule:
#     - cron: '36 */6 * * *'
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        gen: [1]
        options: ['', '-Dshowdown']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: npm install
      # TODO: add integration tests!
      - run: zig build -Drelease-safe ${{matrix.options}} fuzz -- ${{matrix.gen}} 15m
