name: Tests
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        options: ['-Dshowdown', '-Dshowdown -Dtrace', '']
        zig: [0.9.0, master]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - run: git config core.symlinks true
      # TODO: rely on npm postinstall-ed zig for non-master
      # - if: ${{ matrix.zig == 'master' }}
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{matrix.zig}}
      - run: npm install
      # - if: ${{ matrix.zig != 'master' }}
      # - run: echo "${GITHUB_WORKSPACE}/build/bin/zig/zig" >> $GITHUB_PATH
      - run: zig build ${{matrix.options}} -p build
      - run: zig build test ${{matrix.options}}
      - run: zig build test ${{matrix.options}} -Drelease-fast
      - run: zig fmt --check . --exclude build
      - run: npm run compile
      - run: npm test
      - run: npm run test:integration
      - run: npm run lint
      # TODO: test examples