name: Tests
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        options: ['-Dshowdown', '-Dshowdown -Dtrace', '']
        zig: [0.9.0, master]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{matrix.zig}}
      - run: npm install
      - run: zig build ${{matrix.options}} -p build
      - run: zig build test ${{matrix.options}}
      - run: zig build test ${{matrix.options}} -Drelease-fast
      - run: zig fmt --check .
      - run: npm compile
      - npm: npm test
      - run: npm run test:integration
      - run: npm run lint