name: Test
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        options: ['', '-Dtrace', '-Dshowdown', '-Dshowdown -Dtrace']
        zig: [local] # master
    runs-on: ${{matrix.os}}
    steps:
      # - run: exit 0
      #   if: ${{ github.event_name == 'schedule' && matrix.zig != 'master' }}
      - uses: actions/checkout@v3
      - run: git config core.symlinks true
      # NOTE: we rely on npm postinstall-ed zig for local zig
      # - uses: goto-bus-stop/setup-zig@v2
      #   if: ${{ matrix.zig != 'local' }}
      #   with:
      #     version: ${{matrix.zig}}
      - run: npm install
      - run: echo "${GITHUB_WORKSPACE}/build/bin/zig" >> $GITHUB_PATH
        if: ${{ matrix.zig == 'local' && matrix.os != 'windows-latest' }}
      - run: echo "${env:GITHUB_WORKSPACE}/build/bin/zig" >> $env:GITHUB_PATH
        if: ${{ matrix.zig == 'local' && matrix.os == 'windows-latest' }}
      - run: zig build -j1 test ${{matrix.options}}
      - run: zig build -j1 test ${{matrix.options}} -Doptimize=ReleaseFast
      - run: npm run compile
      - run: npm test
      - run: node src/bin/install-pkmn-engine --options="${{matrix.options}}"
      - run: npm run test:integration
      - run: zig build -j1 ${{matrix.options}} -p build
      - run: make example options="${{matrix.options}}"
      - run: make lint
      - run: make clean && node src/bin/install-pkmn-engine --zig
      - run: zig build -j1 ${{matrix.options}} -p build -Ddynamic
      - run: make c-example options="${{matrix.options}}" dynamic=true
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        # DEBUG if: ${{ github.event_name == 'schedule' }}
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: npm install --ignore-scripts
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}